version: '3'

services:
  
  # MariaDB SQL server
  db:
    image: jsurf/rpi-mariadb
    restart: always
    build: ./db
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/log/mysql:/var/log/mysql

  # FastAPI REST API
  app:
    links: 
      - db
    container_name: "api"
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./api