version: '3'

services:
  
  # FastAPI REST API
  app:
    container_name: "api"
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - local-net

networks:
  local-net:
    driver: bridge